CREATE TABLE "pelicula" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar NOT NULL,
  "director_id" varchar NOT NULL,
  "url_img" text,
  "fecha_estreno" varchar NOT NULL
);

CREATE TABLE "director" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "fecha_nacimiento" varchar NOT NULL,
  "nacionalidad" varchar NOT NULL
);

ALTER TABLE "pelicula" ADD FOREIGN KEY ("director_id") REFERENCES "director" ("id");

--
-- Data for Name: director; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.director VALUES (3, 'Quentin', 'Tarantino', '27-03-1963', 'Estadounidense');
INSERT INTO public.director VALUES (4, 'Pedro', 'Almodóvar', '25-09-1949', 'Español');
INSERT INTO public.director VALUES (5, 'Greta', 'Gerwig', '04-08-1983', 'Estadounidense');
INSERT INTO public.director VALUES (6, 'Bong', 'Joon-ho', '14-09-1969', 'Coreano');
INSERT INTO public.director VALUES (7, 'Guillermo', 'del Toro', '09-10-1964', 'Mexicano');
INSERT INTO public.director VALUES (8, 'Sofia', 'Coppola', '14-05-1971', 'Estadounidense');
INSERT INTO public.director VALUES (9, 'Wes', 'Anderson', '01-05-1969', 'Estadounidense');
INSERT INTO public.director VALUES (10, 'Hayao', 'Miyazaki', '05-01-1941', 'Japonés');
INSERT INTO public.director VALUES (1, 'Steven', 'Spielberg', '18-12-1946', 'Estadounidense');
INSERT INTO public.director VALUES (2, 'Christopher', 'Nolan', '30-07-1970', 'Británico');


--
-- Data for Name: pelicula; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pelicula VALUES (3, 'Lady Bird', 5, 'https://musicart.xboxlive.com/7/d1ab5000-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080', '08-09-2017');
INSERT INTO public.pelicula VALUES (4, 'Parásitos', 6, 'https://m.media-amazon.com/images/S/pv-target-images/fb4358b042adbf87a337f58bfc44ca6516388f7d6ed9c69f174cc71e473dab08.jpg', '30-05-2019');
INSERT INTO public.pelicula VALUES (5, 'El laberinto del fauno', 7, 'https://m.media-amazon.com/images/S/pv-target-images/5ea3b0f74fe2901a697365e20b15ac3accdcf68365f9db9aa039f07ae5368165.jpg', '11-10-2006');
INSERT INTO public.pelicula VALUES (1, 'Pulp Fiction', 3, 'https://pics.filmaffinity.com/pulp_fiction-210382116-msmall.jpg', '14-10-1994');
INSERT INTO public.pelicula VALUES (13, 'Mujeres al borde de un ataque de nervios', 4, 'https://pics.filmaffinity.com/mujeres_al_borde_de_un_ataque_de_nervios-287047068-msmall.jpg', '1988');
INSERT INTO public.pelicula VALUES (14, 'Oppenheimer', 2, 'https://pics.filmaffinity.com/oppenheimer-828933592-msmall.jpg', '2023');



